name: CI - Build Backend and Push to GHCR

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GHCR (GitHub Container Registry)
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: TjorvenVannieuwenhuysePXL
          password: ${{ secrets.GHCR_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 

      - name: Build Docker image
        run: docker compose -f docker-compose.yml build

      - name: Tag image as 'latest' and with short commit
        run: |
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)  # Get the short commit hash
          docker tag azulapi ghcr.io/TjorvenVannieuwenhuysePXL/azulapi:latest  # Tag image as 'latest'
          docker tag azulapi ghcr.io/TjorvenVannieuwenhuysePXL/azulapi:$COMMIT_SHA  # Tag image with commit hash

      - name: Push images to GHCR
        run: |
          COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)  # Get the short commit hash
          docker push ghcr.io/TjorvenVannieuwenhuysePXL/azulapi:latest  # Push the 'latest' image
          docker push ghcr.io/TjorvenVannieuwenhuysePXL/azulapi:$COMMIT_SHA  # Push the image with the commit hash
